version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ecr"
      - AWS_REGION="ap-south-1"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  post_build:
    commands:
      - echo "Running the ecr public to private mirror script"
      - bash ecr-pub.sh