version: 0.2

# Execute script to mirror public ECR images to private ECR
# Script source - https://github.com/akto-api-security/infra/blob/infra/aws_ecr_scanning/ecr-pub.sh

phases:
  post_build:
    commands:
      - echo "Running the ecr public to private mirror script"
      - bash ecr-pub.sh