#!/usr/bin/env bash

# NB: local trial script has to be self-contained
# See https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

export MAYBE_SUDO=""
pwd

echo "starting....."

if [ -t 1 ]; then
  export NORMAL="$(tput sgr0)"
  export RED="$(tput setaf 1)"
  export GREEN="$(tput setaf 2)"
  export MAGENTA="$(tput setaf 5)"
  export CYAN="$(tput setaf 6)"
  export WHITE="$(tput setaf 7)"
  export BOLD="$(tput bold)"
else
  export NORMAL=""
  export RED=""
  export GREEN=""
  export MAGENTA=""
  export CYAN=""
  export WHITE=""
  export BOLD=""
fi

$MAYBE_SUDO docker-compose up

echo ""
echo " -- ${GREEN}${BOLD}!! AKTO IS BOOTING !!${NORMAL} --"

WAITED=0

sp="/-\|"
echo -n ' '
i=0
while [ $WAITED -lt 100 ]; do
  WAITED=$((WAITED + 1))
  sleep 0.1
  printf "\b${sp:i++%${#sp}:1}"
done


echo " -- ${GREEN}${BOLD}!! AKTO LAUNCHED !!${NORMAL} --"


# NB: empty stuff to fully wipe out previous line completely
printf "\r%s%s%s%s%s%s%s%s" "$MAGENTA" 'Check out your ' "$BOLD" 'BROWSER' "${NORMAL}${MAGENTA}" ' for some awesomeness!!!' "$NORMAL" '                              '
echo

echo ""
echo "  ${CYAN}Navigate to${NORMAL}:          ${WHITE}${BOLD}http://localhost:8080/login${NORMAL}    or    ${WHITE}${BOLD}[publically_accessible_ip]:8080/login${NORMAL}"
echo ""

echo "Akto was installed in ~/akto. It will run in the background until you manually stop it. If Akto stops you can restart it without losing your data. "

# if command_present open; then
#   open 'http://localhost:8080/login'
# fi

