#!/usr/bin/env bash

# NB: local trial script has to be self-contained
# See https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

export MAYBE_SUDO=""
pwd

echo "starting....."

if [ -t 1 ]; then
  export NORMAL="$(tput sgr0)"
  export RED="$(tput setaf 1)"
  export GREEN="$(tput setaf 2)"
  export MAGENTA="$(tput setaf 5)"
  export CYAN="$(tput setaf 6)"
  export WHITE="$(tput setaf 7)"
  export BOLD="$(tput bold)"
else
  export NORMAL=""
  export RED=""
  export GREEN=""
  export MAGENTA=""
  export CYAN=""
  export WHITE=""
  export BOLD=""
fi

cd ~/akto/infra

$MAYBE_SUDO docker-compose up -d

echo ""
echo " -- ${GREEN}${BOLD}!! AKTO IS BOOTING !!${NORMAL} --"

WAITED=0

sp="/-\|"
echo -n ' '
i=0
while [ $WAITED -lt 100 ]; do
  WAITED=$((WAITED + 1))
  sleep 0.1
  printf "\b${sp:i++%${#sp}:1}"
done


echo " -- ${GREEN}${BOLD}!! Usage collector + processor is up !!${NORMAL} --"

# if command_present open; then
#   open 'http://localhost:8080/login'
# fi

