#!/usr/bin/env bash

# NB: local trial script has to be self-contained
# See https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

export MAYBE_SUDO=""
pwd

echo "starting....."

if [ -t 1 ]; then
  export NORMAL="$(tput sgr0)"
  export RED="$(tput setaf 1)"
  export GREEN="$(tput setaf 2)"
  export MAGENTA="$(tput setaf 5)"
  export CYAN="$(tput setaf 6)"
  export WHITE="$(tput setaf 7)"
  export BOLD="$(tput bold)"
else
  export NORMAL=""
  export RED=""
  export GREEN=""
  export MAGENTA=""
  export CYAN=""
  export WHITE=""
  export BOLD=""
fi

error_exit() {
  echo "${RED}${BOLD}ERROR${NORMAL}${BOLD}: $1${NORMAL}"
  shift
  while [ "$#" -gt "0" ]; do
    echo " - $1"
    shift
  done
  exit 1
}

log_step() {
  echo ''
  echo "${GREEN}${BOLD}INFO${NORMAL}${BOLD}: $1${NORMAL}"
  shift
  while [ "$#" -gt "0" ]; do
    echo " - $1"
    shift
  done
}

log_warn() {
  echo ''
  echo "${GREEN}${BOLD}INFO${NORMAL}${BOLD}: $1${NORMAL}"
  shift
  while [ "$#" -gt "0" ]; do
    echo " - $1"
    shift
  done
}

export DISTRO=$( (lsb_release -ds || cat /etc/*release || uname -om) 2>/dev/null | head -n1)

command_present() {
  type "$1" >/dev/null 2>&1
}

akto_containers_present() {
  # NB: awk is to remove whitespace from `wc`
  AKTO_IMAGES="$($MAYBE_SUDO docker image ls | grep 'akto-api-security' | wc -l | awk '{print $1}')"
  test "$AKTO_IMAGES" -gt '0'
}

akto_trial_running() {
  # NB: awk is to remove whitespace from `wc`
  CONTAINERS="$($MAYBE_SUDO docker-compose ps -q | wc -l | awk '{print $1}')"
  test "$CONTAINERS" -gt '0'
}

# NB: trim trailing slash on $TMPDIR as different OS's do it differently
INSTALL_DIRECTORY="~/akto"
DOCKER_CONTEXT="$INSTALL_DIRECTORY/infra"

cd ~

if [ ! -d "$DOCKER_CONTEXT" ]; then
  if [ -d "$INSTALL_DIRECTORY" ]; then
    log_step 'found a partial install, cleaning it up...'
    rm -rf "$INSTALL_DIRECTORY"
  fi

  log_step 'setting up install location...' "$INSTALL_DIRECTORY"
  mkdir akto && cd akto

  if ! command_present unzip; then
    log_warn '`unzip` not found!'
    log_warn 'Attempting to git clone instead'
    if command_present git; then
      log_step 'cloning...'
      git clone https://github.com/akto-api-security/infra.git
    elif command_present yum; then
      log_warn 'You did not have git so installing'
      sudo yum install git
      git clone https://github.com/akto-api-security/infra.git
    else
      error_exit "Please install git or unzip before continuing"
    fi
  else
    log_step 'downloading...'
    curl -L -XGET -o master.zip https://github.com/akto-api-security/infra/archive/refs/heads/feature/self_hosting.zip
    log_step 'unpacking...'
    unzip master.zip
    mv infra-feature-self_hosting infra
  fi

  # NB: this is to make onprem containers to all get named the same.
  cd infra
  if ! command_present unzip; then
    git checkout feature/self_hosting
  fi
  DOCKER_CONTEXT="$(pwd)"

  log_step 'setting environment variables'
  read -p "Enter your license key: " licenseKey
  echo "LICENSE_KEY=$licenseKey" >> docker.env

  if ! command_present docker; then
    # shellcheck disable=2016
    log_warn '`docker` not found! Attempting to install. This may take a few minutes.'
    chmod 700 ./get-docker.sh
    ./get-docker.sh

    if ! command_present docker; then
      if [[ "$OSTYPE" == "darwin"* ]]; then
        error_exit "please install \`docker\` manually" \
          "Instructions can be found at ${WHITE}${BOLD}https://docs.docker.com/${NORMAL}" \
          "${BOLD}Remember${NORMAL} to start the \`Docker\` app from the UI."
      else
        error_exit "please install \`docker\` manually" \
          "Instructions can be found at ${WHITE}${BOLD}https://docs.docker.com/${NORMAL}" \
          "${BOLD}Remember${NORMAL} to start the \`docker\` daemon/service."
      fi
    fi
  else
    # shellcheck disable=2016
    log_step '`docker` found!'
  fi

  if ! command_present docker-compose; then
    # shellcheck disable=2016
    log_warn '`docker-compose` not found! Attempting to install'
    chmod 700 ./get-docker-compose.sh
    ./get-docker-compose.sh

    if ! command_present docker-compose; then
      if [[ "$OSTYPE" == "darwin"* ]]; then
        error_exit "please install \`docker-compose\` manually" \
          "Usually, \`docker\` and \`docker-compose\` are bundled together, consider uninstalling your existing docker implementation" \
          "Instructions can be found at ${WHITE}${BOLD}https://docs.docker.com/${NORMAL}" \
          "${BOLD}Remember${NORMAL} to start the \`Docker\` app and wait for it to be ${GREEN}${BOLD}READY${NORMAL}."
      else
        error_exit "please install \`docker-compose\` manually" \
          "Usually, \`docker\` and \`docker-compose\` are bundled together, consider uninstalling your existing docker implementation" \
          "Instructions can be found at ${WHITE}${BOLD}https://docs.docker.com/${NORMAL}" \
          "${BOLD}Remember${NORMAL} to start the \`docker\` daemon/service and wait for it to be ${GREEN}${BOLD}READY${NORMAL}."
      fi
    fi
  else
    # shellcheck disable=2016
    log_step '`docker-compose` found!'
  fi

  if [[ $DISTRO == *"CentOS"* ]]; then
    echo 'Starting docker service and making compose accessible by root user'
    if [ ! -f /usr/bin/docker-compose ]; then
      sudo ln -s /usr/local/bin/docker-compose  /usr/bin/docker-compose
    fi
    sudo systemctl enable docker.service
    sudo systemctl start docker.service
  fi

  if akto_containers_present; then
    log_step 'noticed you have tried Akto before, cleaning up...'
    $MAYBE_SUDO docker-compose rm -fsv
  fi
else
  cd "$DOCKER_CONTEXT" || error_exit "Couldn't \`cd\` into '$DOCKER_CONTEXT'" \
    "if you are having repeat issues, you can \`rm -rf $INSTALL_DIRECTORY\`" \
    "if you're still having issues, you can stop all docker containers using the \`docker\` command"
fi

if (! $MAYBE_SUDO docker stats --no-stream) && [ "$OSTYPE" == "linux-gnu" ] && [ "$DISTRO" != "*centos*" ]; then
   sudo docker service start
fi

if akto_trial_running; then
  log_step 'stopping Akto for update...'
  $MAYBE_SUDO docker-compose down
fi


log_step 'updating Akto!'
$MAYBE_SUDO docker-compose pull

log_step "running Akto! ${WHITE}${BOLD}This can take up to 5 minutes${NORMAL}"

#export AKTO_KAFKA_IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)
#echo AKTO_KAFKA_IP=$AKTO_KAFKA_IP >> .env
$MAYBE_SUDO docker-compose up

echo ""
echo " -- ${GREEN}${BOLD}!! AKTO IS BOOTING !!${NORMAL} --"

WAITED=0

sp="/-\|"
echo -n ' '
i=0
while [ $WAITED -lt 100 ]; do
  WAITED=$((WAITED + 1))
  sleep 0.1
  printf "\b${sp:i++%${#sp}:1}"
done


echo " -- ${GREEN}${BOLD}!! AKTO LAUNCHED !!${NORMAL} --"


# NB: empty stuff to fully wipe out previous line completely
printf "\r%s%s%s%s%s%s%s%s" "$MAGENTA" 'Check out your ' "$BOLD" 'BROWSER' "${NORMAL}${MAGENTA}" ' for some awesomeness!!!' "$NORMAL" '                              '
echo

echo ""
echo "  ${CYAN}Navigate to${NORMAL}:          ${WHITE}${BOLD}http://localhost:8080/login${NORMAL}    or    ${WHITE}${BOLD}[publically_accessible_ip]:8080/login${NORMAL}"
echo ""

echo "Akto was installed in ~/akto. It will run in the background until you manually stop it. If Akto stops you can restart it without losing your data. "

if command_present open; then
  open 'http://localhost:8080/login'
fi

