version: '2'

services:
  dependency-graph-jetty:
    image: tangobee/akto-dependency-graph
    restart: always
    ports:
      - "8080:8080"

  dependency-graph-frontend:
    image: tangobee/akto-dependency-graph-frontend
    restart: always
    ports:
      - "80:80"