version: '2.1'

services:
  doom:
    image: public.ecr.aws/aktosecurity/akto-api-security-database-abstractor:doom
    env_file: ./docker-writes-producer.env
    restart: always
    mem_limit: 7g
    ports: 
      - "9001:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "3"
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./watchtower.env
    mem_limit: 200m
    labels:
      com.centurylinklabs.watchtower.enable: "false"
