version: '3'

services:
  flask_server:
    image: ark2307/akto-ssrf-service:latest
    env_file: ./docker.env
    ports:
      - "5200:5100"
    depends_on:
      - redis
    restart: always


  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
volumes:
  redis_data: