version: '2.1'

services:

  prometheus-pushgateway:
    image: prom/pushgateway:latest
    restart: always
    ports:
      - "9091:9091"
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "2"
    mem_limit: 10g
    container_name: prometheus-pushgateway

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
    depends_on:
      - "prometheus-pushgateway"
    mem_limit: 5g
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - "prometheus"
    container_name: grafana
    mem_limit: 1g
    env_file: ./docker-prometheus-grafana.env

volumes:
  grafana-storage:
  prom-data: