version: '3'

services:
  flask_server:
    image: ark2307/akto-ssrf-service:latest
    env_file: ./docker.env
    ports:
      - "5200:5100"
    depends_on:
      - redis
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./watchtower.env
    labels:
      com.centurylinklabs.watchtower.enable: "false"

volumes:
  redis_data: