version: '3.3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    command: mongod --replSet "rs0" --bind_ip ${INSTANCE_IP}
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    network_mode: host