apiVersion: v1
kind: Service
metadata:
  name: mongo-${SETUP_SUFFIX}
  namespace: dev 
spec:
  selector:
    app: mongo-${SETUP_SUFFIX}
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-${SETUP_SUFFIX}
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-${SETUP_SUFFIX}
  template:
    metadata:
      labels:
        app: mongo-${SETUP_SUFFIX}
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017

