apiVersion: apps/v1
kind: Deployment
metadata:
  name: akto-api-security-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akto-api-security-testing
  template:
    metadata:
      labels:
        app: akto-api-security-testing
    spec:
      containers:
        - env:
            - name: AKTO_ACCOUNT_NAME
              value: Helios
            - name: AKTO_CONFIG_NAME
              value: staging
            - name: AKTO_INSTANCE_TYPE
              value: DASHBOARD
            - name: AKTO_KAFKA_BROKER_MAL
              value: localhost:29092
            - name: AKTO_KAFKA_BROKER_URL
              value: kafka1:19092
            - name: AKTO_KAFKA_GROUP_ID_CONFIG
              value: asdf
            - name: AKTO_KAFKA_MAX_POLL_RECORDS_CONFIG
              value: "100"
            - name: AKTO_KAFKA_TOPIC_NAME
              value: akto.api.logs
            - name: AKTO_TRAFFIC_BATCH_SIZE
              value: "100"
            - name: AKTO_TRAFFIC_BATCH_TIME_SECS
              value: "10"
            - name: PUPPETEER_REPLAY_SERVICE_URL
              value: http://akto-puppeteer-replay:3000
            - name: AKTO_MONGO_CONN
              value: mongodb://mongo:27017/admini
          image: aktosecurity/akto-api-testing:mono_staging1_feature_rootless
          name: akto-api-security-testing
          resources: {}
      restartPolicy: Always
