AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DockerTag: 
    Description: 'Tag of docker image'
    Type: String
    Default: 'latest'
Resources:
  TestServersStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://cf-templates-3jie41lht0xk-us-east-1.s3.amazonaws.com/templates/elb-2-instances-test-setup.json
      Parameters: 
        VpcId: vpc-004dbe2e7c81a2256
        Subnets: "subnet-0d3ff2356d5470899,subnet-0490a611ebc996a73,subnet-0858236377f3d70fd"
  AktoStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://cf-templates-3jie41lht0xk-us-east-1.s3.amazonaws.com/templates/akto-setup.yaml
      Parameters: 
        SubnetId: subnet-0d61a1c5e5b46e609
        PublicSubnetIds: "subnet-0d3ff2356d5470899,subnet-0490a611ebc996a73"
        KeyPair: temp1
        SourceLBs: 
          Fn::GetAtt:
            - TestServersStack
            - Outputs.LBName
        DockerTag: !Ref DockerTag

Outputs:
  AktoNLB:
    Value: 
      Fn::GetAtt:
        - AktoStack
        - Outputs.AktoNLB
    Description: Arn of Akto Network Load Balancer
  AktoLBDashboard:
    Value: 
      Fn::GetAtt:
        - AktoStack
        - Outputs.AktoLBDashboard
    Description: Arn of Akto Dashboard Load Balancer
  AktoDashboardUrl:
    Value: 
      Fn::GetAtt:
        - AktoStack
        - Outputs.AktoDashboardUrl
    Description: Akto Dashboard Url
  BooksURL:
    Value: 
      Fn::GetAtt:
        - TestServersStack
        - Outputs.BooksURL
    Description: Url of api/books endpoint
  JuiceShopURL:
    Value: 
      Fn::GetAtt:
        - TestServersStack
        - Outputs.JuiceShopURL
    Description: Url of OWASP Juice Shop
  LBName:
    Value: 
      Fn::GetAtt:
        - TestServersStack
        - Outputs.LBName
    Description: Test server load balancer name