AWSTemplateFormatVersion: 2010-09-09
Resources:
  TestServersStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://cf-templates-3jie41lht0xk-us-east-1.s3.amazonaws.com/templates/elb-2-instances-test-setup.json
      Parameters: 
        Vpc: vpc-004dbe2e7c81a2256
        Subnets: "subnet-0d3ff2356d5470899,subnet-0490a611ebc996a73,subnet-0858236377f3d70fd"
Outputs:
  BooksURL:
    Value: 
      Fn::GetAtt:
        - TestServersStack
        - Outputs.BooksURL
    Description: Url of api/books endpoint
  JuiceShopURL:
    Value: 
      Fn::GetAtt:
        - TestServersStack
        - Outputs.JuiceShopURL
    Description: Url of OWASP Juice Shop
  LBName:
    Value: 
      Fn::GetAtt:
        - TestServersStack
        - Outputs.LBName
    Description: Test server load balancer name